/* qa/qa.js — Bhagavad Gītā Q&A reader. Fetches chapter verse data + the
   per-verse quiz JSON files at request time (no build step), renders
   collapsible verse sections with click-to-reveal answers, bilingual
   toggle, search, and a link to a pre-baked PDF (generated by CI). */

(function () {
  const $ = id => document.getElementById(id);
  let lang = localStorage.getItem('qa_lang') || 'te';

  // Chapters with quiz data available. Extend this list as more chapters
  // get their data/quiz/bg/chNN/ directory filled in.
  const CHAPTERS = [
    { n: 1, te: 'అర్జునవిషాదయోగః', en: "Arjuna's Despondency" },
    { n: 2, te: 'సాంఖ్యయోగః', en: 'Sāṅkhya Yoga' }
  ];

  function pad2(n) { return String(n).padStart(2, '0'); }

  function getChapterFromURL() {
    const params = new URLSearchParams(location.search);
    const n = parseInt(params.get('ch'), 10);
    return CHAPTERS.some(c => c.n === n) ? n : 1;
  }

  function pick(field) {
    if (field && typeof field === 'object' && ('en' in field || 'te' in field)) {
      return field[lang] || field.en || field.te || '';
    }
    return field;
  }

  function normDiacritics(s) {
    return (s || '').toLowerCase()
      .replace(/[ḥṃṁṅñṭḍṇśṣḷ]/g, c => ({ 'ḥ':'h','ṃ':'m','ṁ':'m','ṅ':'n','ñ':'n','ṭ':'t','ḍ':'d','ṇ':'n','ś':'s','ṣ':'s','ḷ':'l' }[c] || c))
      .replace(/[āīūṛṝ]/g, c => ({ 'ā':'a','ī':'i','ū':'u','ṛ':'r','ṝ':'r' }[c] || c));
  }

  async function fetchJSON(url) {
    try {
      const res = await fetch(url);
      if (!res.ok) return null;
      return await res.json();
    } catch (e) {
      return null;
    }
  }

  function verseText(v) {
    return ['p1', 'p2', 'p3', 'p4'].filter(k => v[k]).map(k => v[k].te).join(' | ');
  }

  async function loadChapter(ch) {
    const chTag = `ch${pad2(ch)}`;
    const chData = await fetchJSON(`/data/bg/content/chapters/${chTag}.json`);
    if (!chData) return null;

    const verses = chData.shlokas;
    const quizByVerse = {};

    // Fetch each verse's quiz file, plus optional "5a"/"5b"-style bonus
    // continuation files (present for a few verses, e.g. 1.5a.json).
    await Promise.all(verses.map(async v => {
      const s = v.s;
      const main = await fetchJSON(`/data/quiz/bg/${chTag}/${ch}.${s}.json`);
      let all = main || [];
      for (const suffix of ['a', 'b', 'c']) {
        const extra = await fetchJSON(`/data/quiz/bg/${chTag}/${ch}.${s}${suffix}.json`);
        if (extra) all = all.concat(extra);
        else break;
      }
      if (all.length) quizByVerse[s] = all;
    }));

    return { chData, verses, quizByVerse };
  }

  function renderChoice(c, qBlockEl) {
    const li = document.createElement('li');
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'choice-btn';
    btn.textContent = `${c.id}) ${pick({ en: c.en, te: c.te })}`;
    btn.dataset.correct = c.correct ? 'true' : 'false';
    btn.addEventListener('click', () => {
      if (qBlockEl.dataset.answered === 'true') return;
      qBlockEl.dataset.answered = 'true';
      btn.classList.add(c.correct ? 'picked-correct' : 'picked-wrong');
      qBlockEl.querySelectorAll('.choice-btn').forEach(other => {
        if (other.dataset.correct === 'true') other.classList.add('reveal-correct');
      });
      qBlockEl.querySelector('.answer-block').classList.add('show');
      const revealBtn = qBlockEl.querySelector('.reveal-btn');
      if (revealBtn) revealBtn.remove();
    });
    li.appendChild(btn);
    return li;
  }

  function renderQuestion(q, idx) {
    const block = document.createElement('div');
    block.className = 'q-block';
    block.dataset.answered = 'false';

    const qtext = document.createElement('div');
    qtext.className = 'q-text';
    qtext.innerHTML = `<span class="q-num">${idx}.</span> ${pick({ en: q.q.en, te: q.q.te })}`;
    block.appendChild(qtext);

    const ul = document.createElement('ul');
    ul.className = 'choices';
    q.choices.forEach(c => ul.appendChild(renderChoice(c, block)));
    block.appendChild(ul);

    const reveal = document.createElement('button');
    reveal.className = 'reveal-btn';
    reveal.textContent = lang === 'te' ? 'సమాధానం చూపించు' : 'Show answer';
    reveal.addEventListener('click', () => {
      block.dataset.answered = 'true';
      block.querySelectorAll('.choice-btn').forEach(b => {
        if (b.dataset.correct === 'true') b.classList.add('reveal-correct');
      });
      block.querySelector('.answer-block').classList.add('show');
      reveal.remove();
    });
    block.appendChild(reveal);

    const correct = q.choices.find(c => c.correct);
    const ans = document.createElement('div');
    ans.className = 'answer-block';
    ans.innerHTML = `
      <div class="answer-line">${lang === 'te' ? 'సరైన సమాధానం' : 'Correct answer'}: ${correct.id}) ${pick({ en: correct.en, te: correct.te })}</div>
      <div class="explain">${pick({ en: q.explanation.en, te: q.explanation.te })}</div>
    `;
    block.appendChild(ans);

    return block;
  }

  function renderVerseSection(v, quiz) {
    const det = document.createElement('details');
    det.className = 'verse-section';
    det.id = `v-${v.s}`;
    det.open = v.s === 1;
    const searchable = normDiacritics(JSON.stringify(quiz) + verseText(v));
    det.dataset.searchText = searchable;

    const summary = document.createElement('summary');
    summary.className = 'verse-head';
    summary.innerHTML = `<span class="verse-num">${v.c}.${v.s}</span><span class="verse-qcount">${quiz.length} ${lang === 'te' ? 'ప్రశ్నలు' : 'questions'}</span>`;
    det.appendChild(summary);

    const vcard = document.createElement('div');
    vcard.className = 'verse-card';
    vcard.innerHTML = `
      <div class="verse-sa">${verseText(v)}</div>
      <div class="verse-meaning">${pick({ en: v.meaning.en.short, te: v.meaning.te.short })}</div>
    `;
    det.appendChild(vcard);

    quiz.forEach((q, i) => det.appendChild(renderQuestion(q, i + 1)));
    return det;
  }

  function renderChapterNav(current) {
    const nav = $('chapter-nav');
    nav.innerHTML = CHAPTERS.map(c => {
      const label = `${c.n}. ${lang === 'te' ? c.te : c.en}`;
      return c.n === current
        ? `<span class="current">${label}</span>`
        : `<a href="?ch=${c.n}">${label}</a>`;
    }).join('');
  }

  async function render() {
    const ch = getChapterFromURL();
    const main = $('qa-main');
    main.innerHTML = '<div class="loading" id="qa-loading">Loading…</div>';

    document.querySelectorAll('.script-toggle button').forEach(b => b.classList.toggle('active', b.dataset.lang === lang));
    renderChapterNav(ch);

    const data = await loadChapter(ch);
    if (!data) {
      main.innerHTML = '<div class="loading">Could not load this chapter.</div>';
      return;
    }
    const { chData, verses, quizByVerse } = data;

    $('hero-title').textContent = (lang === 'te' ? 'ప్రశ్నోత్తరాలు — అధ్యాయం ' + ch : 'Q&A — Chapter ' + ch) + ` (${pick(chData.title)})`;
    const totalQ = Object.values(quizByVerse).reduce((s, a) => s + a.length, 0);
    $('hero-sub').textContent = lang === 'te'
      ? `${verses.length} శ్లోకాలు · ${totalQ} ప్రశ్నలు — స్వీయ అధ్యయనం కోసం`
      : `${verses.length} verses · ${totalQ} questions — for self-study`;
    document.title = pick(chData.title) + ' — Q&A · smruti.samskruti.info';

    $('qa-download-pdf').href = `/qa/pdf/bg-ch${pad2(ch)}-te.pdf`;

    main.innerHTML = '';
    verses.forEach(v => {
      const quiz = quizByVerse[v.s];
      if (quiz && quiz.length) main.appendChild(renderVerseSection(v, quiz));
    });
    if (!main.children.length) {
      main.innerHTML = '<div class="loading">No Q&A available for this chapter yet.</div>';
    }
  }

  function setLang(l) {
    lang = l;
    localStorage.setItem('qa_lang', l);
    render();
  }

  function setTheme(t) {
    document.documentElement.setAttribute('data-theme', t);
    localStorage.setItem('qa_theme', t);
    document.querySelectorAll('.theme-toggle button').forEach(b => b.classList.toggle('active', b.dataset.theme === t));
  }

  function applySearch(q) {
    const query = normDiacritics(q.trim());
    document.querySelectorAll('.verse-section').forEach(el => {
      const match = !query || (el.dataset.searchText || '').includes(query);
      el.dataset.hidden = match ? 'false' : 'true';
      if (match && query) el.open = true;
    });
  }

  document.addEventListener('DOMContentLoaded', () => {
    const savedTheme = localStorage.getItem('qa_theme');
    if (savedTheme) setTheme(savedTheme);
    else document.querySelectorAll('.theme-toggle button').forEach(b => b.classList.toggle('active', b.dataset.theme === (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')));

    document.querySelectorAll('.script-toggle button').forEach(b => b.addEventListener('click', () => setLang(b.dataset.lang)));
    document.querySelectorAll('.theme-toggle button').forEach(b => b.addEventListener('click', () => setTheme(b.dataset.theme)));

    $('qa-search').addEventListener('input', e => applySearch(e.target.value));
    $('qa-expand-all').addEventListener('click', () => document.querySelectorAll('.verse-section').forEach(d => d.open = true));
    $('qa-collapse-all').addEventListener('click', () => document.querySelectorAll('.verse-section').forEach(d => d.open = false));

    const backToTop = $('back-to-top');
    window.addEventListener('scroll', () => backToTop.classList.toggle('visible', window.scrollY > 400));
    backToTop.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));

    render();
  });
})();
